Repository 09OndaProject/OndaFront, pull requests merged in 2025-06, with the labels that each got.

#40 [Feature] #24 home UI
  package-lock.json
  package.json
  src/app/page.tsx
  src/assets/images/hero.png
  src/assets/images/homeBanner.png
  src/assets/images/survey1.png
  src/assets/images/survey2.png
  src/assets/images/survey3.png
  src/components/common/DefaultMeetingImage.tsx
  src/components/common/MeetingCard.tsx
  src/components/homeComponents/BannerSection.tsx
  src/components/homeComponents/HeroSection.tsx
  src/components/homeComponents/MainBannerSection.tsx
  src/components/homeComponents/MeetingListSection.tsx
  src/components/homeComponents/MeetingStatusButton.tsx
  src/components/homeComponents/StartSurveySection.tsx
  src/components/homeComponents/SurveyCard.tsx
  src/constants/interestCategory.tsx
  src/datas/meetings.ts
  src/types/meetings.ts
  tailwind.config.js
Labels: feat: 기능추가

#42 [Feature]#34 모임 검색 화면 UI 추가
  src/app/meet/search/page.tsx
  src/components/layout/Header.tsx
  src/components/meet/MeetCard.tsx
  src/components/meet/MeetCardList.tsx
  src/components/meet/MeetFilterBar.tsx
  src/components/meet/MeetSearchBar.tsx
Labels: feat: 기능추가

#43 [Refactor] #39 signup페이지 코드 리펙토링
  src/app/signup/page.tsx
  src/components/common/BirthDateInput.tsx
  src/components/common/LabeledInput.tsx
  src/stores/useSignUpStore.ts
Labels: refactor: 리펙토링

#45 [chore]: meet 관련 파일들 폴더 경로 이동
  src/app/meet/create/_components/MeetForm.tsx
  src/app/meet/create/_components/MeetFormFields.tsx
  src/app/meet/create/_components/MeetImageUploader.tsx
  src/app/meet/create/page.tsx
  src/app/meet/page.tsx
  src/app/meet/search/_components/MeetCard.tsx
  src/app/meet/search/_components/MeetCardList.tsx
  src/app/meet/search/_components/MeetFilterBar.tsx
  src/app/meet/search/_components/MeetSearchBar.tsx
  src/app/meet/search/page.tsx
Labels: chore: 기타 작업

#48 [Refactor]:#44 모임 찾기 페이지 카드 수정
  src/app/meet/create/_components/MeetFormFields.tsx
  src/app/meet/search/_components/MeetCard.tsx
  src/app/meet/search/_components/MeetCardList.tsx
  src/app/meet/search/_components/MeetFilterBar.tsx
  src/components/common/SelectBox.tsx
Labels: refactor: 리펙토링

#52 Feature/#49 finished meet modal
  src/app/_components/MeetingStatusButton.tsx
  src/app/meet/detail/_components/FinishedMeetDetailModal.tsx
  src/app/mypage/page.tsx
  src/components/common/DefaultMeetingImage.tsx
  src/components/common/MeetingCard.tsx
  src/components/common/Modal.tsx
Labels: fix: 버그 수정, feat: 기능추가, style: 스타일 변경

#55 [Feature] #53 kakao login signup UI
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/signup/page.tsx
  src/components/layout/Header.tsx
  src/hooks/useSignupSubmit.ts
  src/stores/useAuth.ts
  src/stores/useSignUpStore.ts
Labels: fix: 버그 수정, feat: 기능추가, style: 스타일 변경

#65 [Design] #64 헤더 반응형 구현
  src/components/layout/Header.tsx
Labels: style: 스타일 변경

#66 [Feature]:#61 모임 상세 정보 모달 생성
  src/app/_components/MeetingStatusButton.tsx
  src/app/meet/review/_components/ReviewWriteModal.tsx
Labels: feat: 기능추가

#71 [Design]: #68 모임 상세 모달 반응형 UI 구현
  src/app/meet/detail/_components/FinishedMeetDetailModal.tsx
  src/app/meet/detail/_components/MeetDetailModal.tsx
Labels: feat: 기능추가, style: 스타일 변경

#74 [Fix] vercel 배포 오류 수정
  package.json
  src/app/meet/create/_components/MeetImageUploader.tsx
  src/app/meet/create/page.tsx
  src/app/meet/detail/_components/FinishedMeetDetailModal.tsx
  src/app/meet/detail/_components/MeetDetailModal.tsx
  src/app/meet/search/_components/MeetCard.tsx
  src/app/meet/search/_components/MeetCardList.tsx
  src/app/meet/search/_components/MeetSearchBar.tsx
Labels: fix: 버그 수정

#77 [Fix]: #76 홈 화면 모임 상세보기 모달 크기 수정 및 필요없는 파일 삭제
  src/app/meet/detail/_components/MeetDetailModal.tsx
  src/app/meet/search/_components/MeetCard.tsx
  src/app/meet/search/_components/MeetCardList.tsx
  src/components/common/Modal.tsx
Labels: fix: 버그 수정

#89 [Feeture] #81 모임 신청 페이지 UI수정
  src/app/meet/create/_components/MeetForm.tsx
  src/app/meet/create/_components/MeetFormFields.tsx
  src/app/meet/create/page.tsx
  src/components/common/AreaSelector.tsx
  src/components/common/SelectBox.tsx
Labels: fix: 버그 수정, feat: 기능추가, style: 스타일 변경

#96 [Feature] #92 로그인 & 회원가입 api 연결
  src/app/login/page.tsx
  src/app/signup/_components/InterestSelector.tsx
  src/app/signup/page.tsx
  src/components/common/AreaSelector.tsx
  src/constants/route.ts
  src/hooks/useSignupSubmit.ts
  src/stores/useAuth.ts
  src/stores/useSignUpStore.ts
Labels: feat: 기능추가

#100 [Feature] #99 관심사 다중 선택 타입 변경 작업
  src/app/signup/_components/InterestSelector.tsx
  src/hooks/useSignupSubmit.ts
  src/stores/useSignUpStore.ts
Labels: feat: 기능추가

#109 [Feature] #101 kakao api로직 구현 및 코드 리펙토링
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/signup/_components/BirthDateInput.tsx
  src/app/signup/_components/DigitalLevelSelector.tsx
  src/app/signup/_components/InterestSelector.tsx
  src/app/signup/page.tsx
  src/app/users/kakao/callback/page.tsx
  src/components/common/AreaSelector.tsx
  src/components/layout/Header.tsx
  src/hooks/useSignupSubmit.ts
  src/stores/useAuth.ts
  src/stores/useSignUpStore.ts
Labels: fix: 버그 수정, feat: 기능추가, refactor: 리펙토링

#111 [Fix] #110 카카오 api 오류 수정 및 보완
  src/hooks/useSignupSubmit.ts
  src/stores/useAuth.ts
Labels: fix: 버그 수정, feat: 기능추가

#113 [Feature] #112 마이페이지 개인 프로필 api 연결
  src/app/mypage/_components/UserProfile.tsx
Labels: feat: 기능추가

#119 [Feature] #118 회원가입 유효성 검증 및 api 오류 해결
  src/apis/app.ts
  src/apis/auth.ts
  src/app/mypage/_components/UserProfile.tsx
  src/app/mypage/edit_profile/page.tsx
  src/app/signup/page.tsx
  src/components/common/TextInput.tsx
  src/hooks/useSignupSubmit.ts
  src/utils/csrf.ts
Labels: fix: 버그 수정, feat: 기능추가

#135 [Fix] #122 refresh fix
  next.config.js
  src/apis/app.ts
  src/apis/auth.ts
  src/app/signup/page.tsx
  src/app/users/verify/email/page.tsx
  src/hooks/useSignupSubmit.ts
  src/stores/useAuth.ts
  src/utils/csrf.ts
Labels: fix: 버그 수정, feat: 기능추가

#142 [Feature] #137 비밀번호 변경 필드 추가 구현
  src/app/mypage/edit_profile/page.tsx
Labels: feat: 기능추가

#149 [Fix] #148 카카오 로그인 오류 해결
  src/app/users/kakao/callback/page.tsx
Labels: fix: 버그 수정

#152 [Fix] #151 사용자 프로필 area 부분 수정 오류 해결
  src/app/mypage/edit_profile/page.tsx
Labels: fix: 버그 수정

#170 [Feature] #161 수정 페이지 구현
  src/app/meet/[meet_id]/edit/page.tsx
  src/app/meet/[meet_id]/page.tsx
  src/app/meet/create/_components/MeetImageUploader.tsx
  src/app/mypage/_components/AppliedScheduleList.tsx
  src/types/meetings.ts
  tsconfig.tsbuildinfo
Labels: feat: 기능추가

#178 [Fix] #173 카카오 사용자 마이페이지 모임 리스트 오류 수정 및 isAdmin 상태 변경
  src/app/mypage/_components/AppliedScheduleList.tsx
  src/app/mypage/_components/PastScheduleList.tsx
  src/app/mypage/page.tsx
  src/stores/useAuth.ts
Labels: fix: 버그 수정
